# Generated by Django 4.2.11 on 2024-06-10 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_number", models.IntegerField(null=True)),
                ("phone_number", models.IntegerField(null=True)),
                ("password", models.CharField(max_length=100, null=True)),
                ("last_login", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("patient_number", models.IntegerField(null=True)),
                ("phone_number", models.IntegerField(null=True)),
                ("height", models.FloatField(null=True)),
                ("weight", models.FloatField(null=True)),
                ("age", models.IntegerField(null=True)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("session_num", models.IntegerField(null=True)),
                (
                    "doc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(null=True)),
                ("session_results", models.CharField(max_length=5000, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.patient",
                    ),
                ),
            ],
        ),
    ]
