# Generated by Django 4.2.11 on 2024-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_session_results_sessions_session_results_l_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
