# Generated by Django 5.0 on 2023-12-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_doctor_phone_number_alter_doctor_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
