# Generated by Django 4.2.11 on 2024-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_doctor_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
