# Generated by Django 4.2.11 on 2024-06-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_doctor_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_staff",
        ),
    ]
