# Generated by Django 5.0 on 2023-12-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pacient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctor'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='pacient_number',
            field=models.IntegerField(null=True),
        ),
    ]
