# Generated by Django 4.2.11 on 2024-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_remove_doctor_is_active_remove_doctor_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
