# Generated by Django 4.2.11 on 2024-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_pacient_doc_alter_pacient_pacient_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacient",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pacient",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
