# Generated by Django 4.2.11 on 2024-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_pacient_age_pacient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacient",
            name="values",
            field=models.FloatField(null=True),
        ),
    ]
