# Generated by Django 4.2.11 on 2024-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_pacient_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacient",
            name="values",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
