# Generated by Django 4.2.11 on 2024-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_sessions_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="session_time",
            field=models.IntegerField(null=True),
        ),
    ]
