# Generated by Django 4.2.11 on 2024-05-01 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_pacient_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacient",
            name="values",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(null=True)),
                ("session_results", models.CharField(max_length=5000, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "Pacient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.pacient",
                    ),
                ),
            ],
        ),
    ]
