# Generated by Django 4.2.11 on 2024-05-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_pacient_values_sessions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pacient",
            old_name="values",
            new_name="seesion_num",
        ),
    ]
