# Generated by Django 4.2.11 on 2024-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_sessions_session_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessions",
            old_name="session_status",
            new_name="session_status_l",
        ),
        migrations.AddField(
            model_name="sessions",
            name="session_status_r",
            field=models.CharField(default="Ongoing", max_length=20, null=True),
        ),
    ]
